version: '3.5'
services:

  benchgraphs-client:
    container_name: benchgraphs-client
    image: 'unum/pystoragedbs:latest'
    volumes:
      - '~/DBs/UnumDB/Graphs/:/var/lib/unumdb'
      - '~/DBs/SQLite/:/var/lib/sqlite'
      - '~/Datasets:~/Datasets'

  # --------------------------
  # DB Servers:
  # --------------------------

  # https://hub.docker.com/_/mongo
  benchgraphs-store-mongo:
    container_name: benchgraphs-store-mongo
    image: 'mongo'
    volumes:
      - '~/benchmarks/mongo:/data/db'
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'temptemp'

  benchgraphs-store-postgres:
    container_name: benchgraphs-store-postgres
    image: 'postgres'
    volumes:
      - '~/benchmarks/postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'temptemp'

  # https://hub.docker.com/_/mysql
  benchgraphs-store-mysql:
    container_name: benchgraphs-store-mysql
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - '~/benchmarks/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'temptemp'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'temptemp'

  # https://hub.docker.com/_/arangodb
  benchgraphs-store-arangodb:
    container_name: benchgraphs-store-arangodb
    image: 'arangodb'
    volumes:
      - '~/benchmarks/arangodb:/var/lib/arangodb3'
    ports:
      - '8529:8529'
    environment:
      ARANGO_STORAGE_ENGINE: 'mmfiles' # 'unumdb'
      ARANGO_ROOT_PASSWORD: 'temptemp'

  benchgraphs-store-neo4j:
    container_name: benchgraphs-store-neo4j
    image: 'neo4j'
    volumes:
      - '~/benchmarks/neo4j:/data'
    ports:
      - '7474:7474' # http
      - '7687:7687' # bolt
    environment:
      NEO4J_AUTH: 'none'
